version: '2'
services:
 
 # mongodb:
 #   image: mongo:latest
 #   container_name: "mongodb"
 #   environment:
 #     - MONGO_DATA_DIR=/data/db
 #     - MONGO_LOG_DIR=/dev/null
 #   volumes:
 #     - ./data/db:/data/db
 #   ports:
 #       - 27017:27017
 #   command: mongod --smallfiles --logpath=/dev/null # --quiet
 #   hostname : mongodb

#mqtt
#  mqtt:
#     image: eclipse-mosquitto:latest
#     restart: always
#     ports:
#       - "1883:1883"
#       - "9001:9001"
#     volumes:
#       - /opt/conf/mqtt/config:/mosquitto/config
#       - /opt/conf/mqtt/data:/mosquitto/data
#       - /opt/conf/mqtt/log:/mosquitto/log
#     hostname : iotmqtt  


#zookeper Kafka      
  kafka:
    image: "wurstmeister/kafka:0.10.2.0"
    ports:
     - "9092:9092"
    #hostname: kafka
    links: 
     - zookeeper
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
     - KAFKA_ZOOKEEPER_CONNECT=192.168.99.100:2181
     - KAFKA_ADVERTISED_PORT=9092
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    #hostname: zookeeper
    
#***********************************************# TOOLS & SERVICES#***********************************************#
# Eureka service registry
#  eureka:
#    build: pmsiot-eureka-server
#    ports:
#    - "8761:8761"
 
# Dashboard microservice UI for admin
  dashboard-spring-app:
    build: pmsiot-dashboard
    ports:
    - "8074:8074"
#    links:
#    - mongodb

# processing-engine microservice From Kafka to Spark - intellegence
  processing-engine:
    build: pmsiot-processing-engine
    ports:
    - "8072:8072"
    links:
#    - mongodb
    - kafka
    - zookeeper

# messaging-rest-api microservice to convert message from MQTT to KAKFA
  messaging-rest-api:
    build: pmsiot-messaging-rest-api
    hostname : iotmessagingrestapi
    ports:
    - "8089:8089"
    - "12345:12345"    
    links:
 #   - mongodb
    - kafka
    - zookeeper
#    - mqtt

# From Kafka to Spark -> MongoDB
  operations:
    build: pmsiot-operations
    ports:
    - "8085:8085"
    links:
 #   - mongodb
    - kafka
    - zookeeper

# From mqtt to restapi
  mqtt-connector:
    build: pmsiot-mqtt-connector
    ports:
    - "8095:8095"
    - "8080:8080"  
#    links:
#    - mqtt

#******************************************# END OF MICROSERVICES #*********************************************#
#################################################################################################################  
